---
name: 'ot-analyze'
author: 'y3rsh'
description: 'A GitHub Action to analyze Opentrons protocols'
inputs:
  BASE_DIRECTORY:
    description: 'relative path in the repository of the root folder in which to search for to search for protocols'
    required: false
    default: 'protocols'
  OUTPUT_TYPE:
    type: choice
    description: 'type of output the action generates'
    required: false
    default: 'none'
    options:
      - 'none'
      - 'zip'
      - 'markdown'
runs:
  using: 'docker'
  # image: 'docker://ghcr.io/y3rsh/ot-analyze:main'
  image: 'Dockerfile'  # For development
branding:
  icon: 'check-square'
  color: 'white'
